### ISSUE TITLE
Currently Not working for me.

### ISSUE THREAD

**Issue by marco3102** [fivetoofive/LethalCompany-DetailedScan#2]
I disabled every mod Exept Terminal API and BepInExPack but the Mod isnt working as intended.
It shows up under "other" with both descirptions.
But when I use either while on a planet I only get Results for 0
The Form is Present at the Bottom and Top with some text but its always completly empty.

**Comment by fivetoofive** [comment]
Thanks for letting me know! I checked the version uploaded to Thunderstore and it is indeed not working. Weirdly, the same version before I uploaded it did work when I went back to check, so I'm guessing the .DLL must have gotten corrupted somehow during the upload process. I re-compiled the .DLL and have submitted it again to Thunderstore, this time I verified that the new version submitted does indeed work. If your still having troubles let me know.

**Comment by marco3102** [comment]
It works again.
Even with all my mods.
Thank you for your record time fixing this.
It is greatly appreceated.
