### ISSUE TITLE
Lately DetailedScan been coming up blank after a round or so

### ISSUE THREAD

**Issue by Kaillera** [fivetoofive/LethalCompany-DetailedScan#4]
Lately DetailedScan been coming up blank after a round or so ever since all the updates to it or TerminalAPI.

**Comment by marco3102** [comment]
I second this.
Could also be related to not being the host.
Have to try. Will update

**Comment by fivetoofive** [comment]
Hey, thanks for letting me know. I haven't been able to replicate the issue yet. But I pushed a patch which may fix it, as I found a major bug while testing for this issue. If you left the match and re-join or join another match without quitting the game, the mod breaks. This might have been what caused the problem. I won't be able to test it when not the host until later tonight though, so let me know if the problem still persists.

**Comment by marco3102** [comment]
Will do. thanks for the patch.

**Comment by fivetoofive** [comment]
I have thoroughly tested the mod both as the host, and not the host and can conclude that no issues have been encountered in the latest version of the mod. If the problem still persists I will open this back up, but for now I'll mark this problem as solved with the most recent patch. Thanks everyone for letting me know!
